/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integradorobjetos.vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Borhamus
 */
public class App extends javax.swing.JFrame {

    public App() {
    initComponents();
    
    // Establecer título y tamaño exacto de la ventana
    setTitle("Universidad Mística Arcana");
    setSize(846, 518); // Dimensiones exactas: 846x518
    setLocationRelativeTo(null);
    setResizable(false); // Evitar que el usuario cambie el tamaño
    
    // Aplicar estilos a la ventana principal
    Style.estiloFrame(this);
    Style.estiloPanel(Fondo, NavBar, Content);
    
    // Aplicar estilos a los botones
    Style.estiloBotonHome(Home);
    Style.estiloBoton(Alumnos, Carreras, PlanDeEstudios);
    
    // Mostrar la vista inicial (vista de noticias)
    Noticias vistaNoticias = new Noticias();
    cambiarVista(vistaNoticias);
}

private void cambiarVista(JPanel nuevaVista) {
    // No establecemos tamaño manual para evitar deformaciones
    // La vista ya tiene sus dimensiones establecidas en su constructor
    
    // Limpiar el panel Content
    Content.removeAll();
    Content.setLayout(new BorderLayout());
    
    // Agregar la nueva vista - usará su tamaño preferido
    Content.add(nuevaVista, BorderLayout.CENTER);
    
    // Actualizar la interfaz
    Content.revalidate();
    Content.repaint();
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        NavBar = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Alumnos = new javax.swing.JButton();
        Carreras = new javax.swing.JButton();
        PlanDeEstudios = new javax.swing.JButton();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(846, 518));
        setMinimumSize(new java.awt.Dimension(846, 518));

        Fondo.setMaximumSize(new java.awt.Dimension(846, 518));
        Fondo.setMinimumSize(new java.awt.Dimension(846, 518));
        Fondo.setPreferredSize(new java.awt.Dimension(846, 518));

        NavBar.setBackground(new java.awt.Color(0, 0, 102));
        NavBar.setMaximumSize(new java.awt.Dimension(846, 120));
        NavBar.setMinimumSize(new java.awt.Dimension(846, 120));

        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Alumnos.setBackground(new java.awt.Color(51, 0, 204));
        Alumnos.setForeground(new java.awt.Color(255, 255, 0));
        Alumnos.setText("Alumnos");
        Alumnos.setMaximumSize(new java.awt.Dimension(80, 20));
        Alumnos.setMinimumSize(new java.awt.Dimension(80, 20));
        Alumnos.setPreferredSize(new java.awt.Dimension(80, 20));
        Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnosActionPerformed(evt);
            }
        });

        Carreras.setBackground(new java.awt.Color(51, 0, 204));
        Carreras.setForeground(new java.awt.Color(255, 255, 0));
        Carreras.setText("Carreras");
        Carreras.setMaximumSize(new java.awt.Dimension(80, 20));
        Carreras.setMinimumSize(new java.awt.Dimension(80, 20));
        Carreras.setPreferredSize(new java.awt.Dimension(80, 20));
        Carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrerasActionPerformed(evt);
            }
        });

        PlanDeEstudios.setBackground(new java.awt.Color(51, 0, 204));
        PlanDeEstudios.setForeground(new java.awt.Color(255, 255, 0));
        PlanDeEstudios.setText("Plan de Estudios");
        PlanDeEstudios.setMaximumSize(new java.awt.Dimension(80, 20));
        PlanDeEstudios.setMinimumSize(new java.awt.Dimension(80, 20));
        PlanDeEstudios.setPreferredSize(new java.awt.Dimension(80, 20));
        PlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanDeEstudiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(NavBarLayout.createSequentialGroup()
                                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))
                        .addGap(32, 32, 32))))
        );

        Content.setMaximumSize(new java.awt.Dimension(846, 398));
        Content.setMinimumSize(new java.awt.Dimension(846, 398));
        Content.setPreferredSize(new java.awt.Dimension(846, 398));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnosActionPerformed
        VistaAlumno1 panel = new VistaAlumno1();
        Content.removeAll();
        Content.setLayout(new BorderLayout());
        Content.add(panel, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_AlumnosActionPerformed

    private void CarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrerasActionPerformed
        VistaCarrera1 panel = new VistaCarrera1();
        Content.removeAll();
        Content.setLayout(new BorderLayout());
        Content.add(panel, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_CarrerasActionPerformed

    private void PlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanDeEstudiosActionPerformed
        VistaPlanDeEstudio panel = new VistaPlanDeEstudio();
        Content.removeAll();
        Content.setLayout(new BorderLayout());
        Content.add(panel, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_PlanDeEstudiosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Noticias panel = new Noticias();
        Content.removeAll();
        Content.setLayout(new BorderLayout());
        Content.add(panel, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alumnos;
    private javax.swing.JButton Carreras;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Home;
    private javax.swing.JPanel NavBar;
    private javax.swing.JButton PlanDeEstudios;
    // End of variables declaration//GEN-END:variables
}
